name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      # Tests

      - name: Run unit tests + coverage
        run: ./gradlew testDebugUnitTest jacocoTestReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
            name: jacoco-report
            path: app/build/reports/jacoco/jacocoTestReport

      - name: Generate coverage badge
        run: |
          COVERAGE=$(grep -o 'line-rate="[^"]*"' app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml \
            | head -n 1 | sed 's/[^0-9.]//g')
          PERCENT=$(echo "$COVERAGE * 100" | bc)
          echo "COVERAGE=$PERCENT" >> $GITHUB_ENV

      - name: Create coverage badge
        run: |
            echo "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen"
    
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with: 
            files: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
            fail_ci_if_error: true

    

